### ISSUE TITLE
Can't run...

### ISSUE THREAD

**Issue by gibsonf1** [cstayyab/WALC#1]
I just tried to install and can't get it to run:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.8.0
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle whatsapp-linux@0.1.0~prestart: whatsapp-linux@0.1.0
6 info lifecycle whatsapp-linux@0.1.0~start: whatsapp-linux@0.1.0
7 verbose lifecycle whatsapp-linux@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle whatsapp-linux@0.1.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/frederick/Downloads/whatsapp-linux/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle whatsapp-linux@0.1.0~start: CWD: /home/frederick/Downloads/whatsapp-linux
10 silly lifecycle whatsapp-linux@0.1.0~start: Args: [ '-c', 'electron .' ]
11 info lifecycle whatsapp-linux@0.1.0~start: Failed to exec start script
12 verbose stack Error: whatsapp-linux@0.1.0 start: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid whatsapp-linux@0.1.0
14 verbose cwd /home/frederick/Downloads/whatsapp-linux
15 verbose Linux 4.18.0-10-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v8.11.4
18 verbose npm  v5.8.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error whatsapp-linux@0.1.0 start: `electron .`
23 error spawn ENOENT
24 error Failed at the whatsapp-linux@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
Any ideas?

Thanks!

**Comment by cstayyab** [comment]
Can you show me the output of `npm install` after you cloned the repo?

**Comment by cstayyab** [comment]
Closed as inactive. Reopen if required.
