### ISSUE TITLE
few errors in terminal

### ISSUE THREAD

**Issue by isete91** [cstayyab/WALC#13]
When running appimage from terminal i get the following errors:
```
Checking for update
Error: Error: This file could not be downloaded, or the latest version (from update server) does not have a valid semver version: "null"
    at newError (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/index.ts:29:17)
    at /tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:306:13
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.isUpdateAvailable (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:303:57)
    at /tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:365:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at AppImageUpdater.checkForUpdatesAndNotify (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/main.js:3:13)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/main.js:214:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/electron.asar/browser/init.js:188:8)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
Unhandled rejection Error: This file could not be downloaded, or the latest version (from update server) does not have a valid semver version: "null"
    at newError (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/index.ts:29:17)
    at /tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:306:13
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.isUpdateAvailable (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:303:57)
    at /tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:365:21
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at AppImageUpdater.checkForUpdatesAndNotify (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/main.js:3:13)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/app.asar/main.js:214:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/electron.asar/browser/init.js:188:8)
    at Object.<anonymous> (/tmp/.mount_WALC-0IUJkUM/resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
```

Also, can you tell me how do i go "offline" for the user if i dont want to appear online all the time?

**Comment by cstayyab** [comment]
These error were related to "Check for Updates". I have fixed them. You can now download the same version (0.14) which is now appearing as (0.1.4). 

>Also, can you tell me how do i go "offline" for the user if i dont want to appear online all the time?

"offline" feature depends on you WhatsApp client on Android/iPhone. Whatsapp Web or WALC cannot do that itself.
