### ISSUE TITLE
Settings icon doesn't appear [Bug Report]

### ISSUE THREAD

**Issue by Rattlyy** [cstayyab/WALC#243]
**Describe the bug**
Settings icon doesn't appear if you use any language other than English, because the aria tag changes.
**WALC Installation Type:** AppImage

**To Reproduce**
1. Change language

**Expected behavior**
Settings icon appearing

**System Information (please complete the following information):**
 - OS/Distro: KDE Neon

**Additional context**
```
TypeError: Cannot read properties of null (reading 'parentElement')
    at Instance.installDashboardIcon (/tmp/.mount_WALC-0lleHOd/resources/app.asar/src/Renderer/Instance.js:38:34)
    at Instance.init (/tmp/.mount_WALC-0lleHOd/resources/app.asar/src/Renderer/Instance.js:17:8)
    at App.init (/tmp/.mount_WALC-0lleHOd/resources/app.asar/src/Renderer/App.js:60:12)
```

**Comment by Rattlyy** [comment]
Please add a way to open settings without using the icon, like an option in the tray.

Workaround (run in dev console):

`require("<app.asar folder, find in Sources tab>/src/Renderer/Instance.js").exec("openDashboard")`

**Comment by sakobm** [comment]
> `require("<app.asar folder, find in Sources tab>/src/Renderer/Instance.js").exec("openDashboard")`

This did not work for me

**Comment by major-mayer** [comment]
Where should the settings icon be?
I didn't even know so far that this app has additional settings to configure and I can't find any icon.

**Comment by sakobm** [comment]
> Where should the settings icon be? I didn't even know so far that this app has additional settings to configure and I can't find any icon.

The icon used to be available at the top bar where chats, community, etc are. Also sometimes when you press ALT, you can see the option. But I realized it takes luck for it to be available. Most of the times it is missing and on few cases, it might launch with the option.

**Comment by major-mayer** [comment]
Hmm definitely not visible for me, also when I press ALT nothing changes.
![grafik](https://github.com/WAClient/WALC/assets/17907799/16399621-7304-4869-a89d-f07e4aac10c4)

**Comment by sakobm** [comment]
> Hmm definitely not visible for me, also when I press ALT nothing changes. ![grafik](https://private-user-images.githubusercontent.com/17907799/326884451-16399621-7304-4869-a89d-f07e4aac10c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTI2OTQsIm5iZiI6MTcxNDQ5MjM5NCwicGF0aCI6Ii8xNzkwNzc5OS8zMjY4ODQ0NTEtMTYzOTk2MjEtNzMwNC00ODY5LWE4OWQtZjA3ZTRhYWMxMGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE1NTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NjQ0YjE2N2Y2YTFkNTRiODNjZjYyZjhiZDI5MTI2OTBhMGM5MjI0ZDYzYjFiMjRjMzMwNTEyMTk3YmFiMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FuZPjgpPmNsuPisCAYeSq20BE6t8WOq1ti8UVlaQCOU)

Like I said it takes luck for it to appear. It used to be in the position I have indicated, bearing the walc logo
![Screenshot_20240430-165049](https://github.com/WAClient/WALC/assets/108432133/8ef631be-1689-4607-8454-bd516389ec74)
